### PR TITLE
Fix #12 - DB access Exceptions handled

### LINKED ISSUE #12: catch sqlite exceptions
currently there is no exception handling

### PR DESCRIPTION
**Pull request by PoLaKoSz**
- Inform User through Snackbar
- Small RegisterViewModel refactoring to keep the method length in readable range

### CODE REVIEW

File: MoodMovies/ViewModels/WatchListViewModel.cs [hunk 1]
```diff
@@ -40,14 +40,25 @@ public async void Handle(AddToWatchListMessage message)
...
-            if (GetMovieCard(movieCard) == null)
+            if (GetMovieCard(movieCard) != null)
+                return;
+
+            try
             {
                 Movies.Add(message.MovieCard);
-            }
 
-            await OfflineDB.AddMovie(CurrentUser, movieCard.Movie);
```
Comment (tonykaralis) [inline MoodMovies/ViewModels/WatchListViewModel.cs]: If I am not mistaken the finally block will always be called. Are you sure you want to try adding a movie  whether it fails or not and then still execute the finally which then removes the movie??

Comment (PoLaKoSz) [reply MoodMovies/ViewModels/WatchListViewModel.cs]: `Movies.Add(message.MovieCard);` adds to the `ObservableCollection<T>` not to the DB (it would be interesting if that fail)
and the finally block just remove from the ObservableCollection if Exception occurred while interacting with DB.

Comment (tonykaralis) [reply MoodMovies/ViewModels/WatchListViewModel.cs]: Yes but if there is no exception after interacting with DB it will still execute the finally and therefore remove what you just added? Is that not correct?

Comment (PoLaKoSz) [reply MoodMovies/ViewModels/WatchListViewModel.cs]: Yes, [You are write](https://stackoverflow.com/a/13545255) I made here a big mistake.

Comment (PoLaKoSz) [reply MoodMovies/ViewModels/WatchListViewModel.cs]: I added the fix and double-checked for finally blocks with the IDE. Should I squash the 2 commit into one and force push to here?

**Comment by tonykaralis** [comment]
Usually I wouldn't squash commits but you can go for it this time.

**Comment by PoLaKoSz** [comment]
I ping @tonykaralis You but I think my commit appeared in your feed.
